version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./backup:/backup
      - ./psql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d boilerplate -U dev" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
