# Generated by Django 3.1.7 on 2021-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_intel_requirement_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelrequirementform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
