# Generated by Django 3.1.7 on 2021-06-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_intel_req_choices_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelrequirementform',
            name='content',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='intelrequirementform',
            name='intelligence_type_code',
            field=models.CharField(choices=[('1', 'Tactical'), ('2', 'Military')], max_length=64),
        ),
        migrations.AlterField(
            model_name='intelrequirementform',
            name='subject',
            field=models.CharField(max_length=64),
        ),
    ]
